apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Define o namespace para todos os recursos
namespace: pit-dev

resources:
- ../../base
- namespace.yaml

patches:
- path: patch-deployment.yaml
- path: patch-ingress.yaml
- path: patch-hpa.yaml

# MERGE com valores específicos de DEVELOPMENT
configMapGenerator:
  - name: pit-config
    behavior: merge
    options:
      disableNameSuffixHash: true
    literals:
      - LOG_LEVEL="debug"
      - MESSAGE="Serviço Admin Development"

images:
- name: dti-registro.unilab.edu.br/unilab/pit
  newTag: dev
