apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pit
spec:
  rules:
    - host: pit.unilab.edu.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pit
                port:
                  number: 80
