apiVersion: apps/v1
kind: Deployment
metadata:
  name: pit
  labels:
    app: pit
spec:
  selector:
    matchLabels:
      app: pit
  template:
    metadata:
      labels:
        app: pit
    spec:
      containers:
      - name: pit
        image: dti-registro.unilab.edu.br/unilab/pit:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        envFrom:
        - configMapRef:
            name: pit-config
        env:
        - name: TZ
          value: "America/Fortaleza"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_CONTAINER_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: pit
              resource: limits.cpu
              divisor: 1m
        - name: KUBERNETES_CONTAINER_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: pit
              resource: limits.memory
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: timezone
          mountPath: /etc/timezone
          readOnly: true
      volumes:
      - name: localtime
        hostPath:
          path: /usr/share/zoneinfo/America/Fortaleza
          type: File
      - name: timezone
        hostPath:
          path: /etc/timezone
          type: File
      imagePullSecrets:
      - name: regcred
